# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58cbd0b359a1d9c3106608bc20121457c49948fb1b3d246be895fddfdbade143a8241d904a9c6729bf3e8bbd62e192b08ac87edc70ea39a155f97843010135f5

test:
  secret_key_base: ca26bd9952876b79c20fe4ce553035b98ce48bdb34c31fc726c88d2b388d75025c39e622784125e95a6c70d9bea3a4d4939a4f6ce7a3c560f53cc35d450f2e88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
